services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=YourStrongPassword123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  maternityhospitalapi:
    build:
      context: .
      dockerfile: MaternityHospitalApi/Dockerfile
    container_name: maternity_hospital_api
    environment:
      - ConnectionStrings__DefaultConnection=Server=tcp:sqlserver,1433;Database=MaternityHospitalDb;User=sa;Password=YourStrongPassword123;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    command: ["wait-for-it", "sqlserver:1433", "--", "dotnet", "MaternityHospitalApi.dll"]

  patientapiclient:
    build:
      context: .
      dockerfile: PatientApiClient/Dockerfile
    container_name: patient_api_client
    depends_on:
      - maternityhospitalapi
    command: ["tail", "-f", "/dev/null"]